package io.simplicity.training.model.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * One entry in a clinician's private journal.
 *
 * <p>There is deliberately no organisation here. These are notes on a person's own practice, and
 * nobody else reads them — not a team admin, not an organisation admin.
 *
 * <p>The {@code search} column is generated by Postgres and is not mapped: Hibernate has no need to
 * read it, and writing it would defeat the point of the database maintaining it.
 */
@Entity
@Table(name = "reflection")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Reflection {

  @Id @GeneratedValue private UUID id;

  @Column(name = "user_id", nullable = false)
  private UUID userId;

  private String title;

  /** Plain text. Nobody but the author reads it, so formatting buys nothing. */
  @Column(nullable = false)
  private String body;

  @CreationTimestamp
  @Column(name = "created_at", nullable = false, updatable = false)
  private Instant createdAt;

  @UpdateTimestamp
  @Column(name = "updated_at", nullable = false)
  private Instant updatedAt;
}
