package io.simplicity.training.controller;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.simplicity.training.model.entity.AppUser;
import io.simplicity.training.support.AbstractIntegrationTest;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;

/**
 * A private journal, so most of these are about what other people cannot see.
 *
 * <p>Reflections carry no organisation and there is no administrative route to them. The tests
 * below are what would fail if either ever changed.
 */
class ReflectionTest extends AbstractIntegrationTest {

  private static final ObjectMapper JSON = new ObjectMapper();
  private static final String ADA = "reflect-ada";
  private static final String GRACE = "reflect-grace";

  @Test
  void writesAndReadsBackOwnReflection() throws Exception {
    String id = write(ADA, "Difficult session", "I noticed I rushed the opening.");

    mockMvc
        .perform(get("/api/v1/me/reflections/{id}", id).header(HttpHeaders.AUTHORIZATION, bearer(ADA)))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.title").value("Difficult session"))
        .andExpect(jsonPath("$.body").value("I noticed I rushed the opening."));
  }

  @Test
  void somebodyElsesReflectionIsNotFoundRatherThanForbidden() throws Exception {
    String id = write(ADA, "Private", "Only for me.");

    // 403 would confirm the id names something real, which is itself a disclosure.
    mockMvc
        .perform(get("/api/v1/me/reflections/{id}", id).header(HttpHeaders.AUTHORIZATION, bearer(GRACE)))
        .andExpect(status().isNotFound());
  }

  @Test
  void theListContainsOnlyTheCallersOwn() throws Exception {
    write(ADA, "Mine", "One.");
    write(GRACE, "Hers", "Two.");

    mockMvc
        .perform(get("/api/v1/me/reflections").header(HttpHeaders.AUTHORIZATION, bearer(ADA)))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.length()").value(1))
        .andExpect(jsonPath("$[0].title").value("Mine"));
  }

  @Test
  void searchFindsAWordInTheBody() throws Exception {
    write(ADA, "Session one", "The client seemed guarded throughout.");
    write(ADA, "Session two", "Much warmer today.");

    mockMvc
        .perform(
            get("/api/v1/me/reflections").param("q", "guarded")
                .header(HttpHeaders.AUTHORIZATION, bearer(ADA)))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.length()").value(1))
        .andExpect(jsonPath("$[0].title").value("Session one"));
  }

  @Test
  void searchFindsAWordInTheTitle() throws Exception {
    write(ADA, "Supervision notes", "Nothing in the body about it.");

    mockMvc
        .perform(
            get("/api/v1/me/reflections").param("q", "supervision")
                .header(HttpHeaders.AUTHORIZATION, bearer(ADA)))
        .andExpect(jsonPath("$.length()").value(1));
  }

  @Test
  void searchMatchesOnStemsRatherThanExactWords() throws Exception {
    write(ADA, null, "I was rushing the opening.");

    // English stemming is why to_tsvector was chosen over a LIKE query.
    mockMvc
        .perform(
            get("/api/v1/me/reflections").param("q", "rush")
                .header(HttpHeaders.AUTHORIZATION, bearer(ADA)))
        .andExpect(jsonPath("$.length()").value(1));
  }

  @Test
  void searchDoesNotReachAnotherCliniciansJournal() throws Exception {
    write(GRACE, "Hers", "A distinctive unrepeatable phrase.");

    mockMvc
        .perform(
            get("/api/v1/me/reflections").param("q", "unrepeatable")
                .header(HttpHeaders.AUTHORIZATION, bearer(ADA)))
        .andExpect(jsonPath("$.length()").value(0));
  }

  @Test
  void editingChangesWhatSearchFinds() throws Exception {
    String id = write(ADA, "Draft", "Originally about listening.");

    mockMvc
        .perform(
            put("/api/v1/me/reflections/{id}", id)
                .header(HttpHeaders.AUTHORIZATION, bearer(ADA))
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"title\":\"Draft\",\"body\":\"Now about pacing instead.\"}"))
        .andExpect(status().isOk());

    // Proves the tsvector really is generated by the database rather than written once on insert.
    mockMvc
        .perform(get("/api/v1/me/reflections").param("q", "pacing")
            .header(HttpHeaders.AUTHORIZATION, bearer(ADA)))
        .andExpect(jsonPath("$.length()").value(1));
    mockMvc
        .perform(get("/api/v1/me/reflections").param("q", "listening")
            .header(HttpHeaders.AUTHORIZATION, bearer(ADA)))
        .andExpect(jsonPath("$.length()").value(0));
  }

  @Test
  void cannotEditSomebodyElses() throws Exception {
    String id = write(ADA, "Mine", "Mine alone.");

    mockMvc
        .perform(
            put("/api/v1/me/reflections/{id}", id)
                .header(HttpHeaders.AUTHORIZATION, bearer(GRACE))
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"body\":\"Tampered.\"}"))
        .andExpect(status().isNotFound());
  }

  @Test
  void deletesOwnAndNotAnothers() throws Exception {
    String mine = write(ADA, "Mine", "Going.");
    String hers = write(GRACE, "Hers", "Staying.");

    mockMvc
        .perform(delete("/api/v1/me/reflections/{id}", mine)
            .header(HttpHeaders.AUTHORIZATION, bearer(ADA)))
        .andExpect(status().isNoContent());
    mockMvc
        .perform(delete("/api/v1/me/reflections/{id}", hers)
            .header(HttpHeaders.AUTHORIZATION, bearer(ADA)))
        .andExpect(status().isNotFound());

    assertThat(reflections.count()).isEqualTo(1);
  }

  @Test
  void refusesAnEmptyReflection() throws Exception {
    mockMvc
        .perform(
            post("/api/v1/me/reflections")
                .header(HttpHeaders.AUTHORIZATION, bearer(ADA))
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"title\":\"Nothing\",\"body\":\"   \"}"))
        .andExpect(status().isBadRequest());
  }

  @Test
  void aJournalGoesWithTheClinicianItBelongedTo() throws Exception {
    write(ADA, "Mine", "Personal.");
    AppUser ada = users.findByCognitoSub(ADA).orElseThrow();

    users.delete(ada);
    users.flush();

    assertThat(reflections.count())
        .as("a private journal has no meaning without the person who wrote it")
        .isZero();
  }

  // -----------------------------------------------------------------------------------------

  private String write(String sub, String title, String body) throws Exception {
    String json =
        title == null
            ? "{\"body\":\"" + body + "\"}"
            : "{\"title\":\"" + title + "\",\"body\":\"" + body + "\"}";
    JsonNode created =
        JSON.readTree(
            mockMvc
                .perform(
                    post("/api/v1/me/reflections")
                        .header(HttpHeaders.AUTHORIZATION, bearer(sub))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(json))
                .andExpect(status().isCreated())
                .andReturn()
                .getResponse()
                .getContentAsString());
    return created.get("id").asText();
  }

  private String bearer(String sub) {
    return tokens.bearerFor(sub, sub + "@example.org");
  }
}
