/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.AnswerInput

class AnswerInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AnswerInput
        //val modelInstance = AnswerInput()

        // to test the property `optionId`
        should("test optionId") {
            // uncomment below to test the property
            //modelInstance.optionId shouldBe ("TODO")
        }

        // to test the property `questionId`
        should("test questionId") {
            // uncomment below to test the property
            //modelInstance.questionId shouldBe ("TODO")
        }

    }
}
