/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.AnswerResponse
import io.simplicity.training.api.models.CitationResponse

class AnswerResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AnswerResponse
        //val modelInstance = AnswerResponse()

        // to test the property `answer`
        should("test answer") {
            // uncomment below to test the property
            //modelInstance.answer shouldBe ("TODO")
        }

        // to test the property `answered`
        should("test answered") {
            // uncomment below to test the property
            //modelInstance.answered shouldBe ("TODO")
        }

        // to test the property `citations`
        should("test citations") {
            // uncomment below to test the property
            //modelInstance.citations shouldBe ("TODO")
        }

    }
}
