/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.AttemptResultResponse
import io.simplicity.training.api.models.MarkedQuestion

class AttemptResultResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AttemptResultResponse
        //val modelInstance = AttemptResultResponse()

        // to test the property `attemptNumber`
        should("test attemptNumber") {
            // uncomment below to test the property
            //modelInstance.attemptNumber shouldBe ("TODO")
        }

        // to test the property `correctCount`
        should("test correctCount") {
            // uncomment below to test the property
            //modelInstance.correctCount shouldBe ("TODO")
        }

        // to test the property `passed`
        should("test passed") {
            // uncomment below to test the property
            //modelInstance.passed shouldBe ("TODO")
        }

        // to test the property `questionCount`
        should("test questionCount") {
            // uncomment below to test the property
            //modelInstance.questionCount shouldBe ("TODO")
        }

        // to test the property `questions`
        should("test questions") {
            // uncomment below to test the property
            //modelInstance.questions shouldBe ("TODO")
        }

    }
}
