/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.AuthoredModuleResponse
import io.simplicity.training.api.models.VersionResponse

class AuthoredModuleResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthoredModuleResponse
        //val modelInstance = AuthoredModuleResponse()

        // to test the property `assignedTeamIds`
        should("test assignedTeamIds") {
            // uncomment below to test the property
            //modelInstance.assignedTeamIds shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `draft`
        should("test draft") {
            // uncomment below to test the property
            //modelInstance.draft shouldBe ("TODO")
        }

        // to test the property `moduleId`
        should("test moduleId") {
            // uncomment below to test the property
            //modelInstance.moduleId shouldBe ("TODO")
        }

        // to test the property `published`
        should("test published") {
            // uncomment below to test the property
            //modelInstance.published shouldBe ("TODO")
        }

        // to test the property `summary`
        should("test summary") {
            // uncomment below to test the property
            //modelInstance.summary shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

    }
}
