/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.ChangeOrgRoleRequest

class ChangeOrgRoleRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChangeOrgRoleRequest
        //val modelInstance = ChangeOrgRoleRequest()

        // to test the property `orgRole`
        should("test orgRole") {
            // uncomment below to test the property
            //modelInstance.orgRole shouldBe ("TODO")
        }

    }
}
