/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.CitationResponse

class CitationResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CitationResponse
        //val modelInstance = CitationResponse()

        // to test the property `assignedToYou`
        should("test assignedToYou") {
            // uncomment below to test the property
            //modelInstance.assignedToYou shouldBe ("TODO")
        }

        // to test the property `moduleId`
        should("test moduleId") {
            // uncomment below to test the property
            //modelInstance.moduleId shouldBe ("TODO")
        }

        // to test the property `moduleTitle`
        should("test moduleTitle") {
            // uncomment below to test the property
            //modelInstance.moduleTitle shouldBe ("TODO")
        }

        // to test the property `sectionTitle`
        should("test sectionTitle") {
            // uncomment below to test the property
            //modelInstance.sectionTitle shouldBe ("TODO")
        }

    }
}
