/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.CreateModuleRequest

class CreateModuleRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateModuleRequest
        //val modelInstance = CreateModuleRequest()

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `summary`
        should("test summary") {
            // uncomment below to test the property
            //modelInstance.summary shouldBe ("TODO")
        }

    }
}
