/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.CurrentUserResponse
import io.simplicity.training.api.models.OrganisationMembershipResponse

class CurrentUserResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CurrentUserResponse
        //val modelInstance = CurrentUserResponse()

        // to test the property `activeOrganisationId`
        should("test activeOrganisationId") {
            // uncomment below to test the property
            //modelInstance.activeOrganisationId shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `fullName`
        should("test fullName") {
            // uncomment below to test the property
            //modelInstance.fullName shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `organisations`
        should("test organisations") {
            // uncomment below to test the property
            //modelInstance.organisations shouldBe ("TODO")
        }

        // to test the property `phone`
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

        // to test the property `platformRole`
        should("test platformRole") {
            // uncomment below to test the property
            //modelInstance.platformRole shouldBe ("TODO")
        }

        // to test the property `professionalRole`
        should("test professionalRole") {
            // uncomment below to test the property
            //modelInstance.professionalRole shouldBe ("TODO")
        }

        // to test the property `profileCompleted`
        should("test profileCompleted") {
            // uncomment below to test the property
            //modelInstance.profileCompleted shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
