/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.InvitationPreviewResponse

class InvitationPreviewResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvitationPreviewResponse
        //val modelInstance = InvitationPreviewResponse()

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `orgRole`
        should("test orgRole") {
            // uncomment below to test the property
            //modelInstance.orgRole shouldBe ("TODO")
        }

        // to test the property `organisationName`
        should("test organisationName") {
            // uncomment below to test the property
            //modelInstance.organisationName shouldBe ("TODO")
        }

        // to test the property `teamName`
        should("test teamName") {
            // uncomment below to test the property
            //modelInstance.teamName shouldBe ("TODO")
        }

        // to test the property `valid`
        should("test valid") {
            // uncomment below to test the property
            //modelInstance.valid shouldBe ("TODO")
        }

    }
}
