/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.LearnerModuleResponse
import io.simplicity.training.api.models.SectionResponse

class LearnerModuleResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LearnerModuleResponse
        //val modelInstance = LearnerModuleResponse()

        // to test the property `completedSectionIds`
        should("test completedSectionIds") {
            // uncomment below to test the property
            //modelInstance.completedSectionIds shouldBe ("TODO")
        }

        // to test the property `hasQuiz`
        should("test hasQuiz") {
            // uncomment below to test the property
            //modelInstance.hasQuiz shouldBe ("TODO")
        }

        // to test the property `moduleId`
        should("test moduleId") {
            // uncomment below to test the property
            //modelInstance.moduleId shouldBe ("TODO")
        }

        // to test the property `quizPassed`
        should("test quizPassed") {
            // uncomment below to test the property
            //modelInstance.quizPassed shouldBe ("TODO")
        }

        // to test the property `sections`
        should("test sections") {
            // uncomment below to test the property
            //modelInstance.sections shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `summary`
        should("test summary") {
            // uncomment below to test the property
            //modelInstance.summary shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `versionId`
        should("test versionId") {
            // uncomment below to test the property
            //modelInstance.versionId shouldBe ("TODO")
        }

    }
}
