/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.MarkedQuestion

class MarkedQuestionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MarkedQuestion
        //val modelInstance = MarkedQuestion()

        // to test the property `chosenOptionId`
        should("test chosenOptionId") {
            // uncomment below to test the property
            //modelInstance.chosenOptionId shouldBe ("TODO")
        }

        // to test the property `correctOptionId`
        should("test correctOptionId") {
            // uncomment below to test the property
            //modelInstance.correctOptionId shouldBe ("TODO")
        }

        // to test the property `explanation`
        should("test explanation") {
            // uncomment below to test the property
            //modelInstance.explanation shouldBe ("TODO")
        }

        // to test the property `prompt`
        should("test prompt") {
            // uncomment below to test the property
            //modelInstance.prompt shouldBe ("TODO")
        }

        // to test the property `questionId`
        should("test questionId") {
            // uncomment below to test the property
            //modelInstance.questionId shouldBe ("TODO")
        }

        // to test the property `wasCorrect`
        should("test wasCorrect") {
            // uncomment below to test the property
            //modelInstance.wasCorrect shouldBe ("TODO")
        }

    }
}
