/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.MediaAssetResponse

class MediaAssetResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MediaAssetResponse
        //val modelInstance = MediaAssetResponse()

        // to test the property `assetId`
        should("test assetId") {
            // uncomment below to test the property
            //modelInstance.assetId shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `durationSeconds`
        should("test durationSeconds") {
            // uncomment below to test the property
            //modelInstance.durationSeconds shouldBe ("TODO")
        }

        // to test the property `failureReason`
        should("test failureReason") {
            // uncomment below to test the property
            //modelInstance.failureReason shouldBe ("TODO")
        }

        // to test the property `filename`
        should("test filename") {
            // uncomment below to test the property
            //modelInstance.filename shouldBe ("TODO")
        }

        // to test the property `hasCaptions`
        should("test hasCaptions") {
            // uncomment below to test the property
            //modelInstance.hasCaptions shouldBe ("TODO")
        }

        // to test the property `sizeBytes`
        should("test sizeBytes") {
            // uncomment below to test the property
            //modelInstance.sizeBytes shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
