/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.ModuleSummaryResponse

class ModuleSummaryResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ModuleSummaryResponse
        //val modelInstance = ModuleSummaryResponse()

        // to test the property `assignedTeamCount`
        should("test assignedTeamCount") {
            // uncomment below to test the property
            //modelInstance.assignedTeamCount shouldBe ("TODO")
        }

        // to test the property `hasDraft`
        should("test hasDraft") {
            // uncomment below to test the property
            //modelInstance.hasDraft shouldBe ("TODO")
        }

        // to test the property `moduleId`
        should("test moduleId") {
            // uncomment below to test the property
            //modelInstance.moduleId shouldBe ("TODO")
        }

        // to test the property `publishedVersion`
        should("test publishedVersion") {
            // uncomment below to test the property
            //modelInstance.publishedVersion shouldBe ("TODO")
        }

        // to test the property `summary`
        should("test summary") {
            // uncomment below to test the property
            //modelInstance.summary shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

    }
}
