/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.OrganisationMembershipResponse
import io.simplicity.training.api.models.TeamMembershipResponse

class OrganisationMembershipResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrganisationMembershipResponse
        //val modelInstance = OrganisationMembershipResponse()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `orgId`
        should("test orgId") {
            // uncomment below to test the property
            //modelInstance.orgId shouldBe ("TODO")
        }

        // to test the property `orgRole`
        should("test orgRole") {
            // uncomment below to test the property
            //modelInstance.orgRole shouldBe ("TODO")
        }

        // to test the property `organisationType`
        should("test organisationType") {
            // uncomment below to test the property
            //modelInstance.organisationType shouldBe ("TODO")
        }

        // to test the property `slug`
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `teams`
        should("test teams") {
            // uncomment below to test the property
            //modelInstance.teams shouldBe ("TODO")
        }

    }
}
