/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.OrgMemberResponse

class OrgMemberResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrgMemberResponse
        //val modelInstance = OrgMemberResponse()

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `fullName`
        should("test fullName") {
            // uncomment below to test the property
            //modelInstance.fullName shouldBe ("TODO")
        }

        // to test the property `joinedAt`
        should("test joinedAt") {
            // uncomment below to test the property
            //modelInstance.joinedAt shouldBe ("TODO")
        }

        // to test the property `membershipStatus`
        should("test membershipStatus") {
            // uncomment below to test the property
            //modelInstance.membershipStatus shouldBe ("TODO")
        }

        // to test the property `orgRole`
        should("test orgRole") {
            // uncomment below to test the property
            //modelInstance.orgRole shouldBe ("TODO")
        }

        // to test the property `professionalRole`
        should("test professionalRole") {
            // uncomment below to test the property
            //modelInstance.professionalRole shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `userStatus`
        should("test userStatus") {
            // uncomment below to test the property
            //modelInstance.userStatus shouldBe ("TODO")
        }

    }
}
