/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.PlaybackResponse

class PlaybackResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlaybackResponse
        //val modelInstance = PlaybackResponse()

        // to test the property `captionUrl`
        should("test captionUrl") {
            // uncomment below to test the property
            //modelInstance.captionUrl shouldBe ("TODO")
        }

        // to test the property `expiresInSeconds`
        should("test expiresInSeconds") {
            // uncomment below to test the property
            //modelInstance.expiresInSeconds shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
