/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.QuestionInput
import io.simplicity.training.api.models.OptionInput

class QuestionInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QuestionInput
        //val modelInstance = QuestionInput()

        // to test the property `options`
        should("test options") {
            // uncomment below to test the property
            //modelInstance.options shouldBe ("TODO")
        }

        // to test the property `prompt`
        should("test prompt") {
            // uncomment below to test the property
            //modelInstance.prompt shouldBe ("TODO")
        }

        // to test the property `explanation`
        should("test explanation") {
            // uncomment below to test the property
            //modelInstance.explanation shouldBe ("TODO")
        }

    }
}
