/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.QuizResponse
import io.simplicity.training.api.models.QuizQuestionResponse

class QuizResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QuizResponse
        //val modelInstance = QuizResponse()

        // to test the property `attemptCount`
        should("test attemptCount") {
            // uncomment below to test the property
            //modelInstance.attemptCount shouldBe ("TODO")
        }

        // to test the property `passed`
        should("test passed") {
            // uncomment below to test the property
            //modelInstance.passed shouldBe ("TODO")
        }

        // to test the property `questions`
        should("test questions") {
            // uncomment below to test the property
            //modelInstance.questions shouldBe ("TODO")
        }

        // to test the property `versionId`
        should("test versionId") {
            // uncomment below to test the property
            //modelInstance.versionId shouldBe ("TODO")
        }

    }
}
