/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.RegisterUploadRequest

class RegisterUploadRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RegisterUploadRequest
        //val modelInstance = RegisterUploadRequest()

        // to test the property `contentType`
        should("test contentType") {
            // uncomment below to test the property
            //modelInstance.contentType shouldBe ("TODO")
        }

        // to test the property `filename`
        should("test filename") {
            // uncomment below to test the property
            //modelInstance.filename shouldBe ("TODO")
        }

        // to test the property `sizeBytes`
        should("test sizeBytes") {
            // uncomment below to test the property
            //modelInstance.sizeBytes shouldBe ("TODO")
        }

    }
}
