/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.ReplaceSectionsRequest
import io.simplicity.training.api.models.SectionInput

class ReplaceSectionsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReplaceSectionsRequest
        //val modelInstance = ReplaceSectionsRequest()

        // to test the property `sections`
        should("test sections") {
            // uncomment below to test the property
            //modelInstance.sections shouldBe ("TODO")
        }

    }
}
