/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.ReplaceQuizRequest
import io.simplicity.training.api.models.QuestionInput

class ReplaceQuizRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReplaceQuizRequest
        //val modelInstance = ReplaceQuizRequest()

        // to test the property `questions`
        should("test questions") {
            // uncomment below to test the property
            //modelInstance.questions shouldBe ("TODO")
        }

    }
}
