/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.SubmitAttemptRequest
import io.simplicity.training.api.models.AnswerInput

class SubmitAttemptRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubmitAttemptRequest
        //val modelInstance = SubmitAttemptRequest()

        // to test the property `answers`
        should("test answers") {
            // uncomment below to test the property
            //modelInstance.answers shouldBe ("TODO")
        }

    }
}
