/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.models.VersionResponse
import io.simplicity.training.api.models.AuthoredQuestionResponse
import io.simplicity.training.api.models.SectionResponse

class VersionResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VersionResponse
        //val modelInstance = VersionResponse()

        // to test the property `publishedAt`
        should("test publishedAt") {
            // uncomment below to test the property
            //modelInstance.publishedAt shouldBe ("TODO")
        }

        // to test the property `questions`
        should("test questions") {
            // uncomment below to test the property
            //modelInstance.questions shouldBe ("TODO")
        }

        // to test the property `sections`
        should("test sections") {
            // uncomment below to test the property
            //modelInstance.sections shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `supersedesCompletions`
        should("test supersedesCompletions") {
            // uncomment below to test the property
            //modelInstance.supersedesCompletions shouldBe ("TODO")
        }

        // to test the property `versionId`
        should("test versionId") {
            // uncomment below to test the property
            //modelInstance.versionId shouldBe ("TODO")
        }

        // to test the property `versionNumber`
        should("test versionNumber") {
            // uncomment below to test the property
            //modelInstance.versionNumber shouldBe ("TODO")
        }

    }
}
