/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.apis.AssistantApi
import io.simplicity.training.api.models.AnswerResponse
import io.simplicity.training.api.models.AskRequest

class AssistantApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AssistantApi
        //val apiInstance = AssistantApi()

        // to test askAssistant
        should("test askAssistant") {
            // uncomment below to test askAssistant
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val askRequest : AskRequest =  // AskRequest | 
            //val result : AnswerResponse = apiInstance.askAssistant(orgId, askRequest)
            //result shouldBe ("TODO")
        }

    }
}
