/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.apis.CurrentUserApi
import io.simplicity.training.api.models.CurrentUserResponse
import io.simplicity.training.api.models.SetActiveOrganisationRequest
import io.simplicity.training.api.models.UpdateProfileRequest

class CurrentUserApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CurrentUserApi
        //val apiInstance = CurrentUserApi()

        // to test getCurrentUser
        should("test getCurrentUser") {
            // uncomment below to test getCurrentUser
            //val result : CurrentUserResponse = apiInstance.getCurrentUser()
            //result shouldBe ("TODO")
        }

        // to test setActiveOrganisation
        should("test setActiveOrganisation") {
            // uncomment below to test setActiveOrganisation
            //val setActiveOrganisationRequest : SetActiveOrganisationRequest =  // SetActiveOrganisationRequest | 
            //val result : CurrentUserResponse = apiInstance.setActiveOrganisation(setActiveOrganisationRequest)
            //result shouldBe ("TODO")
        }

        // to test updateProfile
        should("test updateProfile") {
            // uncomment below to test updateProfile
            //val updateProfileRequest : UpdateProfileRequest =  // UpdateProfileRequest | 
            //val result : CurrentUserResponse = apiInstance.updateProfile(updateProfileRequest)
            //result shouldBe ("TODO")
        }

    }
}
