/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.apis.InvitationsApi
import io.simplicity.training.api.models.CreateInvitationRequest
import io.simplicity.training.api.models.InvitationPreviewResponse
import io.simplicity.training.api.models.InvitationResponse

class InvitationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvitationsApi
        //val apiInstance = InvitationsApi()

        // to test acceptInvitation
        should("test acceptInvitation") {
            // uncomment below to test acceptInvitation
            //val token : kotlin.String = token_example // kotlin.String | 
            //apiInstance.acceptInvitation(token)
        }

        // to test createInvitation
        should("test createInvitation") {
            // uncomment below to test createInvitation
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val createInvitationRequest : CreateInvitationRequest =  // CreateInvitationRequest | 
            //val result : InvitationResponse = apiInstance.createInvitation(orgId, createInvitationRequest)
            //result shouldBe ("TODO")
        }

        // to test listInvitations
        should("test listInvitations") {
            // uncomment below to test listInvitations
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : kotlin.collections.List<InvitationResponse> = apiInstance.listInvitations(orgId)
            //result shouldBe ("TODO")
        }

        // to test previewInvitation
        should("test previewInvitation") {
            // uncomment below to test previewInvitation
            //val token : kotlin.String = token_example // kotlin.String | 
            //val result : InvitationPreviewResponse = apiInstance.previewInvitation(token)
            //result shouldBe ("TODO")
        }

        // to test revokeInvitation
        should("test revokeInvitation") {
            // uncomment below to test revokeInvitation
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val invitationId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.revokeInvitation(orgId, invitationId)
        }

    }
}
