/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.apis.LearningApi
import io.simplicity.training.api.models.AssignedModuleResponse
import io.simplicity.training.api.models.AttemptResultResponse
import io.simplicity.training.api.models.LearnerModuleResponse
import io.simplicity.training.api.models.PlaybackResponse
import io.simplicity.training.api.models.QuizResponse
import io.simplicity.training.api.models.SubmitAttemptRequest

class LearningApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LearningApi
        //val apiInstance = LearningApi()

        // to test completeSection
        should("test completeSection") {
            // uncomment below to test completeSection
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val sectionId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : LearnerModuleResponse = apiInstance.completeSection(orgId, sectionId)
            //result shouldBe ("TODO")
        }

        // to test getPlaybackUrl
        should("test getPlaybackUrl") {
            // uncomment below to test getPlaybackUrl
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val assetId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : PlaybackResponse = apiInstance.getPlaybackUrl(orgId, assetId)
            //result shouldBe ("TODO")
        }

        // to test getQuiz
        should("test getQuiz") {
            // uncomment below to test getQuiz
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : QuizResponse = apiInstance.getQuiz(orgId, moduleId)
            //result shouldBe ("TODO")
        }

        // to test listAssignedModules
        should("test listAssignedModules") {
            // uncomment below to test listAssignedModules
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : kotlin.collections.List<AssignedModuleResponse> = apiInstance.listAssignedModules(orgId)
            //result shouldBe ("TODO")
        }

        // to test readModule
        should("test readModule") {
            // uncomment below to test readModule
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : LearnerModuleResponse = apiInstance.readModule(orgId, moduleId)
            //result shouldBe ("TODO")
        }

        // to test submitQuizAttempt
        should("test submitQuizAttempt") {
            // uncomment below to test submitQuizAttempt
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val submitAttemptRequest : SubmitAttemptRequest =  // SubmitAttemptRequest | 
            //val result : AttemptResultResponse = apiInstance.submitQuizAttempt(orgId, moduleId, submitAttemptRequest)
            //result shouldBe ("TODO")
        }

    }
}
