/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.apis.MediaApi
import io.simplicity.training.api.models.MediaAssetResponse
import io.simplicity.training.api.models.RegisterUploadRequest
import io.simplicity.training.api.models.UploadTargetResponse

class MediaApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MediaApi
        //val apiInstance = MediaApi()

        // to test completeUpload
        should("test completeUpload") {
            // uncomment below to test completeUpload
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val assetId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : MediaAssetResponse = apiInstance.completeUpload(orgId, assetId)
            //result shouldBe ("TODO")
        }

        // to test deleteMedia
        should("test deleteMedia") {
            // uncomment below to test deleteMedia
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val assetId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteMedia(orgId, assetId)
        }

        // to test listMedia
        should("test listMedia") {
            // uncomment below to test listMedia
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : kotlin.collections.List<MediaAssetResponse> = apiInstance.listMedia(orgId)
            //result shouldBe ("TODO")
        }

        // to test registerUpload
        should("test registerUpload") {
            // uncomment below to test registerUpload
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val registerUploadRequest : RegisterUploadRequest =  // RegisterUploadRequest | 
            //val result : UploadTargetResponse = apiInstance.registerUpload(orgId, registerUploadRequest)
            //result shouldBe ("TODO")
        }

        // to test removeCaptions
        should("test removeCaptions") {
            // uncomment below to test removeCaptions
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val assetId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : MediaAssetResponse = apiInstance.removeCaptions(orgId, assetId)
            //result shouldBe ("TODO")
        }

        // to test setCaptions
        should("test setCaptions") {
            // uncomment below to test setCaptions
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val assetId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val body : kotlin.String = body_example // kotlin.String | 
            //val result : MediaAssetResponse = apiInstance.setCaptions(orgId, assetId, body)
            //result shouldBe ("TODO")
        }

    }
}
