/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.apis.ModulesApi
import io.simplicity.training.api.models.AssignTeamsRequest
import io.simplicity.training.api.models.AuthoredModuleResponse
import io.simplicity.training.api.models.CreateModuleRequest
import io.simplicity.training.api.models.ModuleSummaryResponse
import io.simplicity.training.api.models.PublishRequest
import io.simplicity.training.api.models.ReplaceQuizRequest
import io.simplicity.training.api.models.ReplaceSectionsRequest
import io.simplicity.training.api.models.UpdateModuleRequest

class ModulesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ModulesApi
        //val apiInstance = ModulesApi()

        // to test archiveModule
        should("test archiveModule") {
            // uncomment below to test archiveModule
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.archiveModule(orgId, moduleId)
        }

        // to test assignModuleToTeams
        should("test assignModuleToTeams") {
            // uncomment below to test assignModuleToTeams
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val assignTeamsRequest : AssignTeamsRequest =  // AssignTeamsRequest | 
            //val result : AuthoredModuleResponse = apiInstance.assignModuleToTeams(orgId, moduleId, assignTeamsRequest)
            //result shouldBe ("TODO")
        }

        // to test createModule
        should("test createModule") {
            // uncomment below to test createModule
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val createModuleRequest : CreateModuleRequest =  // CreateModuleRequest | 
            //val result : AuthoredModuleResponse = apiInstance.createModule(orgId, createModuleRequest)
            //result shouldBe ("TODO")
        }

        // to test getModule
        should("test getModule") {
            // uncomment below to test getModule
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : AuthoredModuleResponse = apiInstance.getModule(orgId, moduleId)
            //result shouldBe ("TODO")
        }

        // to test listModules
        should("test listModules") {
            // uncomment below to test listModules
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : kotlin.collections.List<ModuleSummaryResponse> = apiInstance.listModules(orgId)
            //result shouldBe ("TODO")
        }

        // to test openModuleDraft
        should("test openModuleDraft") {
            // uncomment below to test openModuleDraft
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : AuthoredModuleResponse = apiInstance.openModuleDraft(orgId, moduleId)
            //result shouldBe ("TODO")
        }

        // to test publishModule
        should("test publishModule") {
            // uncomment below to test publishModule
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val publishRequest : PublishRequest =  // PublishRequest | 
            //val result : AuthoredModuleResponse = apiInstance.publishModule(orgId, moduleId, publishRequest)
            //result shouldBe ("TODO")
        }

        // to test replaceModuleQuiz
        should("test replaceModuleQuiz") {
            // uncomment below to test replaceModuleQuiz
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val replaceQuizRequest : ReplaceQuizRequest =  // ReplaceQuizRequest | 
            //val result : AuthoredModuleResponse = apiInstance.replaceModuleQuiz(orgId, moduleId, replaceQuizRequest)
            //result shouldBe ("TODO")
        }

        // to test replaceModuleSections
        should("test replaceModuleSections") {
            // uncomment below to test replaceModuleSections
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val replaceSectionsRequest : ReplaceSectionsRequest =  // ReplaceSectionsRequest | 
            //val result : AuthoredModuleResponse = apiInstance.replaceModuleSections(orgId, moduleId, replaceSectionsRequest)
            //result shouldBe ("TODO")
        }

        // to test updateModule
        should("test updateModule") {
            // uncomment below to test updateModule
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val moduleId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val updateModuleRequest : UpdateModuleRequest =  // UpdateModuleRequest | 
            //val result : AuthoredModuleResponse = apiInstance.updateModule(orgId, moduleId, updateModuleRequest)
            //result shouldBe ("TODO")
        }

    }
}
