/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.apis.OrganisationsApi
import io.simplicity.training.api.models.ChangeOrgRoleRequest
import io.simplicity.training.api.models.CreateOrganisationRequest
import io.simplicity.training.api.models.OrgMemberResponse
import io.simplicity.training.api.models.OrganisationResponse

class OrganisationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrganisationsApi
        //val apiInstance = OrganisationsApi()

        // to test archiveOrganisation
        should("test archiveOrganisation") {
            // uncomment below to test archiveOrganisation
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.archiveOrganisation(orgId)
        }

        // to test changeOrganisationRole
        should("test changeOrganisationRole") {
            // uncomment below to test changeOrganisationRole
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val userId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val changeOrgRoleRequest : ChangeOrgRoleRequest =  // ChangeOrgRoleRequest | 
            //val result : OrgMemberResponse = apiInstance.changeOrganisationRole(orgId, userId, changeOrgRoleRequest)
            //result shouldBe ("TODO")
        }

        // to test createOrganisation
        should("test createOrganisation") {
            // uncomment below to test createOrganisation
            //val createOrganisationRequest : CreateOrganisationRequest =  // CreateOrganisationRequest | 
            //val result : OrganisationResponse = apiInstance.createOrganisation(createOrganisationRequest)
            //result shouldBe ("TODO")
        }

        // to test getOrganisation
        should("test getOrganisation") {
            // uncomment below to test getOrganisation
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : OrganisationResponse = apiInstance.getOrganisation(orgId)
            //result shouldBe ("TODO")
        }

        // to test leaveOrganisation
        should("test leaveOrganisation") {
            // uncomment below to test leaveOrganisation
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.leaveOrganisation(orgId)
        }

        // to test listOrganisationMembers
        should("test listOrganisationMembers") {
            // uncomment below to test listOrganisationMembers
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : kotlin.collections.List<OrgMemberResponse> = apiInstance.listOrganisationMembers(orgId)
            //result shouldBe ("TODO")
        }

        // to test removeOrganisationMember
        should("test removeOrganisationMember") {
            // uncomment below to test removeOrganisationMember
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val userId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.removeOrganisationMember(orgId, userId)
        }

    }
}
