/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.apis.ReflectionsApi
import io.simplicity.training.api.models.ReflectionResponse
import io.simplicity.training.api.models.WriteReflectionRequest

class ReflectionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReflectionsApi
        //val apiInstance = ReflectionsApi()

        // to test deleteReflection
        should("test deleteReflection") {
            // uncomment below to test deleteReflection
            //val reflectionId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteReflection(reflectionId)
        }

        // to test editReflection
        should("test editReflection") {
            // uncomment below to test editReflection
            //val reflectionId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val writeReflectionRequest : WriteReflectionRequest =  // WriteReflectionRequest | 
            //val result : ReflectionResponse = apiInstance.editReflection(reflectionId, writeReflectionRequest)
            //result shouldBe ("TODO")
        }

        // to test getReflection
        should("test getReflection") {
            // uncomment below to test getReflection
            //val reflectionId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : ReflectionResponse = apiInstance.getReflection(reflectionId)
            //result shouldBe ("TODO")
        }

        // to test listReflections
        should("test listReflections") {
            // uncomment below to test listReflections
            //val q : kotlin.String = q_example // kotlin.String | 
            //val result : kotlin.collections.List<ReflectionResponse> = apiInstance.listReflections(q)
            //result shouldBe ("TODO")
        }

        // to test writeReflection
        should("test writeReflection") {
            // uncomment below to test writeReflection
            //val writeReflectionRequest : WriteReflectionRequest =  // WriteReflectionRequest | 
            //val result : ReflectionResponse = apiInstance.writeReflection(writeReflectionRequest)
            //result shouldBe ("TODO")
        }

    }
}
