/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.simplicity.training.api.apis.TeamsApi
import io.simplicity.training.api.models.AddTeamMemberRequest
import io.simplicity.training.api.models.CreateTeamRequest
import io.simplicity.training.api.models.TeamMemberDetailResponse
import io.simplicity.training.api.models.TeamResponse
import io.simplicity.training.api.models.UpdateTeamRequest

class TeamsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TeamsApi
        //val apiInstance = TeamsApi()

        // to test addTeamMember
        should("test addTeamMember") {
            // uncomment below to test addTeamMember
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val teamId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val addTeamMemberRequest : AddTeamMemberRequest =  // AddTeamMemberRequest | 
            //val result : TeamMemberDetailResponse = apiInstance.addTeamMember(orgId, teamId, addTeamMemberRequest)
            //result shouldBe ("TODO")
        }

        // to test createTeam
        should("test createTeam") {
            // uncomment below to test createTeam
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val createTeamRequest : CreateTeamRequest =  // CreateTeamRequest | 
            //val result : TeamResponse = apiInstance.createTeam(orgId, createTeamRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteTeam
        should("test deleteTeam") {
            // uncomment below to test deleteTeam
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val teamId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteTeam(orgId, teamId)
        }

        // to test getTeam
        should("test getTeam") {
            // uncomment below to test getTeam
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val teamId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : TeamResponse = apiInstance.getTeam(orgId, teamId)
            //result shouldBe ("TODO")
        }

        // to test listTeamMembers
        should("test listTeamMembers") {
            // uncomment below to test listTeamMembers
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val teamId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : kotlin.collections.List<TeamMemberDetailResponse> = apiInstance.listTeamMembers(orgId, teamId)
            //result shouldBe ("TODO")
        }

        // to test listTeams
        should("test listTeams") {
            // uncomment below to test listTeams
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : kotlin.collections.List<TeamResponse> = apiInstance.listTeams(orgId)
            //result shouldBe ("TODO")
        }

        // to test removeTeamMember
        should("test removeTeamMember") {
            // uncomment below to test removeTeamMember
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val teamId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val userId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.removeTeamMember(orgId, teamId, userId)
        }

        // to test updateTeam
        should("test updateTeam") {
            // uncomment below to test updateTeam
            //val orgId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val teamId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val updateTeamRequest : UpdateTeamRequest =  // UpdateTeamRequest | 
            //val result : TeamResponse = apiInstance.updateTeam(orgId, teamId, updateTeamRequest)
            //result shouldBe ("TODO")
        }

    }
}
