disabled_rules:
  - line_length
  - todo

opt_in_rules:
  - empty_string
  - force_unwrapping
  - implicit_return
  - modifier_order
  - sorted_imports

excluded:
  - Packages/SimplicityApi/Sources/SimplicityApi/Generated
  - .build
  - DerivedData

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 600
