export * from './assistant.service';
import { AssistantApi } from './assistant.service';
export * from './assistant.serviceInterface';
export * from './current-user.service';
import { CurrentUserApi } from './current-user.service';
export * from './current-user.serviceInterface';
export * from './invitations.service';
import { InvitationsApi } from './invitations.service';
export * from './invitations.serviceInterface';
export * from './learning.service';
import { LearningApi } from './learning.service';
export * from './learning.serviceInterface';
export * from './media.service';
import { MediaApi } from './media.service';
export * from './media.serviceInterface';
export * from './modules.service';
import { ModulesApi } from './modules.service';
export * from './modules.serviceInterface';
export * from './organisations.service';
import { OrganisationsApi } from './organisations.service';
export * from './organisations.serviceInterface';
export * from './reflections.service';
import { ReflectionsApi } from './reflections.service';
export * from './reflections.serviceInterface';
export * from './teams.service';
import { TeamsApi } from './teams.service';
export * from './teams.serviceInterface';
export const APIS = [AssistantApi, CurrentUserApi, InvitationsApi, LearningApi, MediaApi, ModulesApi, OrganisationsApi, ReflectionsApi, TeamsApi];
