/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CurrentUserResponse } from '../model/models';
import { SetActiveOrganisationRequest } from '../model/models';
import { UpdateProfileRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CurrentUserApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Describe the signed-in user
     * Provisions the user on first call. Clients use profileCompleted and the organisations list to decide whether to show onboarding.
     * @endpoint get /api/v1/me
     */
    getCurrentUser(extraHttpRequestParams?: any): Observable<CurrentUserResponse>;

    /**
     * Choose which organisation to work in
     * Stored on the user so the choice follows them to another device. Refused for any organisation that is not a live membership of the caller\&#39;s.
     * @endpoint put /api/v1/me/active-organisation
     * @param setActiveOrganisationRequest 
     */
    setActiveOrganisation(setActiveOrganisationRequest: SetActiveOrganisationRequest, extraHttpRequestParams?: any): Observable<CurrentUserResponse>;

    /**
     * Complete or update the professional profile
     * Sets profileCompleted, which is what lets the client leave the wizard.
     * @endpoint put /api/v1/me/profile
     * @param updateProfileRequest 
     */
    updateProfile(updateProfileRequest: UpdateProfileRequest, extraHttpRequestParams?: any): Observable<CurrentUserResponse>;

}
