/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateInvitationRequest } from '../model/models';
import { InvitationPreviewResponse } from '../model/models';
import { InvitationResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InvitationsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Accept an invitation as the signed-in user
     * 
     * @endpoint post /api/v1/invitations/{token}/accept
     * @param token 
     */
    accept(token: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Invite somebody to the organisation
     * Re-inviting an address withdraws the outstanding invitation and issues a fresh link, so only one token is ever live for a given address.
     * @endpoint post /api/v1/orgs/{orgId}/invitations
     * @param orgId 
     * @param createInvitationRequest 
     */
    create1(orgId: string, createInvitationRequest: CreateInvitationRequest, extraHttpRequestParams?: any): Observable<InvitationResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/orgs/{orgId}/invitations
     * @param orgId 
     */
    list1(orgId: string, extraHttpRequestParams?: any): Observable<Array<InvitationResponse>>;

    /**
     * Preview an invitation before signing up
     * Public. Returns valid&#x3D;false for anything unknown, expired, or already used, so the endpoint cannot be used to probe for live tokens.
     * @endpoint get /api/v1/invitations/{token}
     * @param token 
     */
    preview(token: string, extraHttpRequestParams?: any): Observable<InvitationPreviewResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/orgs/{orgId}/invitations/{invitationId}
     * @param orgId 
     * @param invitationId 
     */
    revoke(orgId: string, invitationId: string, extraHttpRequestParams?: any): Observable<{}>;

}
