/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AssignedModuleResponse } from '../model/models';
import { AttemptResultResponse } from '../model/models';
import { LearnerModuleResponse } from '../model/models';
import { QuizResponse } from '../model/models';
import { SubmitAttemptRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LearningApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Mark a section as read
     * Completing the last section completes the module in the same transaction.
     * @endpoint put /api/v1/orgs/{orgId}/learning/sections/{sectionId}/complete
     * @param orgId 
     * @param sectionId 
     */
    completeSection(orgId: string, sectionId: string, extraHttpRequestParams?: any): Observable<LearnerModuleResponse>;

    /**
     * The quiz for an assigned module
     * Questions and options only. Which option is correct is never sent here.
     * @endpoint get /api/v1/orgs/{orgId}/learning/{moduleId}/quiz
     * @param orgId 
     * @param moduleId 
     */
    getQuiz(orgId: string, moduleId: string, extraHttpRequestParams?: any): Observable<QuizResponse>;

    /**
     * Modules assigned to the caller\&#39;s teams, with their progress
     * 
     * @endpoint get /api/v1/orgs/{orgId}/learning
     * @param orgId 
     */
    listAssignedModules(orgId: string, extraHttpRequestParams?: any): Observable<Array<AssignedModuleResponse>>;

    /**
     * The published version of one assigned module
     * 
     * @endpoint get /api/v1/orgs/{orgId}/learning/{moduleId}
     * @param orgId 
     * @param moduleId 
     */
    readModule(orgId: string, moduleId: string, extraHttpRequestParams?: any): Observable<LearnerModuleResponse>;

    /**
     * Answer the quiz
     * Marked on the server. Returns which questions were right, the correct answer, and the author\&#39;s explanation. Passing completes the module if every section is read.
     * @endpoint post /api/v1/orgs/{orgId}/learning/{moduleId}/quiz/attempts
     * @param orgId 
     * @param moduleId 
     * @param submitAttemptRequest 
     */
    submitQuizAttempt(orgId: string, moduleId: string, submitAttemptRequest: SubmitAttemptRequest, extraHttpRequestParams?: any): Observable<AttemptResultResponse>;

}
