/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AssignedModuleResponse } from '../model/models';
import { LearnerModuleResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LearningApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Mark a section as read
     * Completing the last section completes the module in the same transaction.
     * @endpoint put /api/v1/orgs/{orgId}/learning/sections/{sectionId}/complete
     * @param orgId 
     * @param sectionId 
     */
    completeSection(orgId: string, sectionId: string, extraHttpRequestParams?: any): Observable<LearnerModuleResponse>;

    /**
     * Modules assigned to the caller\&#39;s teams, with their progress
     * 
     * @endpoint get /api/v1/orgs/{orgId}/learning
     * @param orgId 
     */
    listAssignedModules(orgId: string, extraHttpRequestParams?: any): Observable<Array<AssignedModuleResponse>>;

    /**
     * The published version of one assigned module
     * 
     * @endpoint get /api/v1/orgs/{orgId}/learning/{moduleId}
     * @param orgId 
     * @param moduleId 
     */
    readModule(orgId: string, moduleId: string, extraHttpRequestParams?: any): Observable<LearnerModuleResponse>;

}
