/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MediaAssetResponse } from '../model/models';
import { RegisterUploadRequest } from '../model/models';
import { UploadTargetResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MediaApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Report that the upload finished
     * Hands the file to the transcoder; the asset becomes PROCESSING.
     * @endpoint post /api/v1/orgs/{orgId}/media/{assetId}/uploaded
     * @param orgId 
     * @param assetId 
     */
    completeUpload(orgId: string, assetId: string, extraHttpRequestParams?: any): Observable<MediaAssetResponse>;

    /**
     * Delete a video
     * Any section using it keeps its writing and loses the video.
     * @endpoint delete /api/v1/orgs/{orgId}/media/{assetId}
     * @param orgId 
     * @param assetId 
     */
    deleteMedia(orgId: string, assetId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * The organisation\&#39;s video library
     * 
     * @endpoint get /api/v1/orgs/{orgId}/media
     * @param orgId 
     */
    listMedia(orgId: string, extraHttpRequestParams?: any): Observable<Array<MediaAssetResponse>>;

    /**
     * Register a video and get somewhere to put it
     * Returns a presigned URL the browser PUTs to directly. Video never passes through the API on the way in.
     * @endpoint post /api/v1/orgs/{orgId}/media
     * @param orgId 
     * @param registerUploadRequest 
     */
    registerUpload(orgId: string, registerUploadRequest: RegisterUploadRequest, extraHttpRequestParams?: any): Observable<UploadTargetResponse>;

    /**
     * Remove the caption track
     * 
     * @endpoint delete /api/v1/orgs/{orgId}/media/{assetId}/captions
     * @param orgId 
     * @param assetId 
     */
    removeCaptions(orgId: string, assetId: string, extraHttpRequestParams?: any): Observable<MediaAssetResponse>;

    /**
     * Attach a WebVTT caption track
     * Sent as the request body rather than presigned, because a caption file is kilobytes where a video is hundreds of megabytes.
     * @endpoint put /api/v1/orgs/{orgId}/media/{assetId}/captions
     * @param orgId 
     * @param assetId 
     * @param body 
     */
    setCaptions(orgId: string, assetId: string, body: string, extraHttpRequestParams?: any): Observable<MediaAssetResponse>;

}
