/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AssignTeamsRequest } from '../model/models';
import { AuthoredModuleResponse } from '../model/models';
import { CreateModuleRequest } from '../model/models';
import { ModuleSummaryResponse } from '../model/models';
import { PublishRequest } from '../model/models';
import { ReplaceQuizRequest } from '../model/models';
import { ReplaceSectionsRequest } from '../model/models';
import { UpdateModuleRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ModulesApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Archive a module
     * Hidden from learners and authors alike. Completions and history are kept.
     * @endpoint delete /api/v1/orgs/{orgId}/modules/{moduleId}
     * @param orgId 
     * @param moduleId 
     */
    archiveModule(orgId: string, moduleId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Set which teams this module is assigned to
     * 
     * @endpoint put /api/v1/orgs/{orgId}/modules/{moduleId}/teams
     * @param orgId 
     * @param moduleId 
     * @param assignTeamsRequest 
     */
    assignModuleToTeams(orgId: string, moduleId: string, assignTeamsRequest: AssignTeamsRequest, extraHttpRequestParams?: any): Observable<AuthoredModuleResponse>;

    /**
     * Create a module
     * Comes with an empty first draft, since a module with no version cannot be edited.
     * @endpoint post /api/v1/orgs/{orgId}/modules
     * @param orgId 
     * @param createModuleRequest 
     */
    createModule(orgId: string, createModuleRequest: CreateModuleRequest, extraHttpRequestParams?: any): Observable<AuthoredModuleResponse>;

    /**
     * One module, with both the published version and the draft
     * 
     * @endpoint get /api/v1/orgs/{orgId}/modules/{moduleId}
     * @param orgId 
     * @param moduleId 
     */
    getModule(orgId: string, moduleId: string, extraHttpRequestParams?: any): Observable<AuthoredModuleResponse>;

    /**
     * List this organisation\&#39;s modules
     * 
     * @endpoint get /api/v1/orgs/{orgId}/modules
     * @param orgId 
     */
    listModules(orgId: string, extraHttpRequestParams?: any): Observable<Array<ModuleSummaryResponse>>;

    /**
     * Open a draft
     * Copies what learners currently have, so an edit starts from the live content.
     * @endpoint post /api/v1/orgs/{orgId}/modules/{moduleId}/draft
     * @param orgId 
     * @param moduleId 
     */
    openModuleDraft(orgId: string, moduleId: string, extraHttpRequestParams?: any): Observable<AuthoredModuleResponse>;

    /**
     * Publish the draft
     * Set supersedesCompletions when the change is substantive, which sends anyone who completed an earlier version back through it. A corrected typo should not.
     * @endpoint post /api/v1/orgs/{orgId}/modules/{moduleId}/draft/publish
     * @param orgId 
     * @param moduleId 
     * @param publishRequest 
     */
    publishModule(orgId: string, moduleId: string, publishRequest: PublishRequest, extraHttpRequestParams?: any): Observable<AuthoredModuleResponse>;

    /**
     * Replace the draft\&#39;s quiz questions
     * Each question needs at least two options and exactly one correct one; publishing refuses anything else, since a question with no answer can never be passed.
     * @endpoint put /api/v1/orgs/{orgId}/modules/{moduleId}/draft/quiz
     * @param orgId 
     * @param moduleId 
     * @param replaceQuizRequest 
     */
    replaceModuleQuiz(orgId: string, moduleId: string, replaceQuizRequest: ReplaceQuizRequest, extraHttpRequestParams?: any): Observable<AuthoredModuleResponse>;

    /**
     * Replace the draft\&#39;s sections
     * Sent whole: editing, reordering, and deleting all happen on one screen.
     * @endpoint put /api/v1/orgs/{orgId}/modules/{moduleId}/draft/sections
     * @param orgId 
     * @param moduleId 
     * @param replaceSectionsRequest 
     */
    replaceModuleSections(orgId: string, moduleId: string, replaceSectionsRequest: ReplaceSectionsRequest, extraHttpRequestParams?: any): Observable<AuthoredModuleResponse>;

    /**
     * Rename a module or change its summary
     * 
     * @endpoint patch /api/v1/orgs/{orgId}/modules/{moduleId}
     * @param orgId 
     * @param moduleId 
     * @param updateModuleRequest 
     */
    updateModule(orgId: string, moduleId: string, updateModuleRequest: UpdateModuleRequest, extraHttpRequestParams?: any): Observable<AuthoredModuleResponse>;

}
