/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChangeOrgRoleRequest } from '../model/models';
import { CreateOrganisationRequest } from '../model/models';
import { OrgMemberResponse } from '../model/models';
import { OrganisationResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OrganisationsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Change a member\&#39;s organisation role
     * 
     * @endpoint patch /api/v1/orgs/{orgId}/members/{userId}
     * @param orgId 
     * @param userId 
     * @param changeOrgRoleRequest 
     */
    changeRole(orgId: string, userId: string, changeOrgRoleRequest: ChangeOrgRoleRequest, extraHttpRequestParams?: any): Observable<OrgMemberResponse>;

    /**
     * Create an organisation
     * The caller becomes its first administrator. Used by the self-signup flow.
     * @endpoint post /api/v1/organisations
     * @param createOrganisationRequest 
     */
    create2(createOrganisationRequest: CreateOrganisationRequest, extraHttpRequestParams?: any): Observable<OrganisationResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/orgs/{orgId}
     * @param orgId 
     */
    get1(orgId: string, extraHttpRequestParams?: any): Observable<OrganisationResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/orgs/{orgId}/members
     * @param orgId 
     */
    listMembers1(orgId: string, extraHttpRequestParams?: any): Observable<Array<OrgMemberResponse>>;

    /**
     * Remove a member, ending their team memberships in this organisation
     * 
     * @endpoint delete /api/v1/orgs/{orgId}/members/{userId}
     * @param orgId 
     * @param userId 
     */
    removeMember(orgId: string, userId: string, extraHttpRequestParams?: any): Observable<{}>;

}
