/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChangeOrgRoleRequest } from '../model/models';
import { CreateOrganisationRequest } from '../model/models';
import { OrgMemberResponse } from '../model/models';
import { OrganisationResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OrganisationsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Archive an organisation
     * Makes it unreachable for every member while keeping its memberships, teams, and audit history. Nothing is deleted.
     * @endpoint delete /api/v1/orgs/{orgId}
     * @param orgId 
     */
    archiveOrganisation(orgId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Change a member\&#39;s organisation role
     * 
     * @endpoint patch /api/v1/orgs/{orgId}/members/{userId}
     * @param orgId 
     * @param userId 
     * @param changeOrgRoleRequest 
     */
    changeOrganisationRole(orgId: string, userId: string, changeOrgRoleRequest: ChangeOrgRoleRequest, extraHttpRequestParams?: any): Observable<OrgMemberResponse>;

    /**
     * Create an organisation
     * The caller becomes its first administrator. Used by the self-signup flow.
     * @endpoint post /api/v1/organisations
     * @param createOrganisationRequest 
     */
    createOrganisation(createOrganisationRequest: CreateOrganisationRequest, extraHttpRequestParams?: any): Observable<OrganisationResponse>;

    /**
     * Fetch one organisation
     * 
     * @endpoint get /api/v1/orgs/{orgId}
     * @param orgId 
     */
    getOrganisation(orgId: string, extraHttpRequestParams?: any): Observable<OrganisationResponse>;

    /**
     * Leave an organisation
     * Ends the caller\&#39;s own membership and their teams within it. The last administrator may leave, which archives the organisation rather than leaving nobody able to administer it.
     * @endpoint delete /api/v1/orgs/{orgId}/members/me
     * @param orgId 
     */
    leaveOrganisation(orgId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * List everybody in an organisation
     * 
     * @endpoint get /api/v1/orgs/{orgId}/members
     * @param orgId 
     */
    listOrganisationMembers(orgId: string, extraHttpRequestParams?: any): Observable<Array<OrgMemberResponse>>;

    /**
     * Remove a member, ending their team memberships in this organisation
     * 
     * @endpoint delete /api/v1/orgs/{orgId}/members/{userId}
     * @param orgId 
     * @param userId 
     */
    removeOrganisationMember(orgId: string, userId: string, extraHttpRequestParams?: any): Observable<{}>;

}
