/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ReflectionResponse } from '../model/models';
import { WriteReflectionRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReflectionsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete one
     * 
     * @endpoint delete /api/v1/me/reflections/{reflectionId}
     * @param reflectionId 
     */
    deleteReflection(reflectionId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Edit one
     * 
     * @endpoint put /api/v1/me/reflections/{reflectionId}
     * @param reflectionId 
     * @param writeReflectionRequest 
     */
    editReflection(reflectionId: string, writeReflectionRequest: WriteReflectionRequest, extraHttpRequestParams?: any): Observable<ReflectionResponse>;

    /**
     * Read one
     * Somebody else\&#39;s returns 404, because a 403 would confirm that it exists.
     * @endpoint get /api/v1/me/reflections/{reflectionId}
     * @param reflectionId 
     */
    getReflection(reflectionId: string, extraHttpRequestParams?: any): Observable<ReflectionResponse>;

    /**
     * The caller\&#39;s reflections, newest first, or those matching a search
     * 
     * @endpoint get /api/v1/me/reflections
     * @param q 
     */
    listReflections(q?: string, extraHttpRequestParams?: any): Observable<Array<ReflectionResponse>>;

    /**
     * Write a reflection
     * 
     * @endpoint post /api/v1/me/reflections
     * @param writeReflectionRequest 
     */
    writeReflection(writeReflectionRequest: WriteReflectionRequest, extraHttpRequestParams?: any): Observable<ReflectionResponse>;

}
