/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddTeamMemberRequest } from '../model/models';
import { CreateTeamRequest } from '../model/models';
import { TeamMemberDetailResponse } from '../model/models';
import { TeamResponse } from '../model/models';
import { UpdateTeamRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TeamsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add an organisation member to a team
     * 
     * @endpoint post /api/v1/orgs/{orgId}/teams/{teamId}/members
     * @param orgId 
     * @param teamId 
     * @param addTeamMemberRequest 
     */
    addTeamMember(orgId: string, teamId: string, addTeamMemberRequest: AddTeamMemberRequest, extraHttpRequestParams?: any): Observable<TeamMemberDetailResponse>;

    /**
     * Create a team
     * Restricted to organisation administrators; team administrators cannot.
     * @endpoint post /api/v1/orgs/{orgId}/teams
     * @param orgId 
     * @param createTeamRequest 
     */
    createTeam(orgId: string, createTeamRequest: CreateTeamRequest, extraHttpRequestParams?: any): Observable<TeamResponse>;

    /**
     * Delete a team
     * Organisation administrators only. A team administrator can manage their team\&#39;s membership but cannot remove the team itself.
     * @endpoint delete /api/v1/orgs/{orgId}/teams/{teamId}
     * @param orgId 
     * @param teamId 
     */
    deleteTeam(orgId: string, teamId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Fetch one team
     * 
     * @endpoint get /api/v1/orgs/{orgId}/teams/{teamId}
     * @param orgId 
     * @param teamId 
     */
    getTeam(orgId: string, teamId: string, extraHttpRequestParams?: any): Observable<TeamResponse>;

    /**
     * List the people in a team
     * 
     * @endpoint get /api/v1/orgs/{orgId}/teams/{teamId}/members
     * @param orgId 
     * @param teamId 
     */
    listTeamMembers(orgId: string, teamId: string, extraHttpRequestParams?: any): Observable<Array<TeamMemberDetailResponse>>;

    /**
     * List the teams in an organisation
     * 
     * @endpoint get /api/v1/orgs/{orgId}/teams
     * @param orgId 
     */
    listTeams(orgId: string, extraHttpRequestParams?: any): Observable<Array<TeamResponse>>;

    /**
     * Remove somebody from a team
     * 
     * @endpoint delete /api/v1/orgs/{orgId}/teams/{teamId}/members/{userId}
     * @param orgId 
     * @param teamId 
     * @param userId 
     */
    removeTeamMember(orgId: string, teamId: string, userId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Rename or redescribe a team
     * 
     * @endpoint patch /api/v1/orgs/{orgId}/teams/{teamId}
     * @param orgId 
     * @param teamId 
     * @param updateTeamRequest 
     */
    updateTeam(orgId: string, teamId: string, updateTeamRequest: UpdateTeamRequest, extraHttpRequestParams?: any): Observable<TeamResponse>;

}
