/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param teamRole 
 * @param userId 
 */
@Serializable

data class AddTeamMemberRequest (

    @SerialName(value = "teamRole")
    val teamRole: AddTeamMemberRequest.TeamRole,

    @Contextual @SerialName(value = "userId")
    val userId: java.util.UUID

) {

    /**
     * 
     *
     * Values: TEAM_ADMIN,TEAM_MEMBER
     */
    @Serializable
    enum class TeamRole(val value: kotlin.String) {
        @SerialName(value = "TEAM_ADMIN") TEAM_ADMIN("TEAM_ADMIN"),
        @SerialName(value = "TEAM_MEMBER") TEAM_MEMBER("TEAM_MEMBER");
    }

}

