/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.simplicity.training.api.models.CitationResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param answer 
 * @param answered 
 * @param citations 
 */
@Serializable

data class AnswerResponse (

    @SerialName(value = "answer")
    val answer: kotlin.String? = null,

    @SerialName(value = "answered")
    val answered: kotlin.Boolean? = null,

    @SerialName(value = "citations")
    val citations: kotlin.collections.List<CitationResponse>? = null

) {


}

