/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param completedSectionCount 
 * @param hasQuiz 
 * @param moduleId 
 * @param quizPassed 
 * @param sectionCount 
 * @param status 
 * @param summary 
 * @param title 
 * @param versionId 
 */
@Serializable

data class AssignedModuleResponse (

    @SerialName(value = "completedSectionCount")
    val completedSectionCount: kotlin.Int? = null,

    @SerialName(value = "hasQuiz")
    val hasQuiz: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "moduleId")
    val moduleId: java.util.UUID? = null,

    @SerialName(value = "quizPassed")
    val quizPassed: kotlin.Boolean? = null,

    @SerialName(value = "sectionCount")
    val sectionCount: kotlin.Int? = null,

    @SerialName(value = "status")
    val status: AssignedModuleResponse.Status? = null,

    @SerialName(value = "summary")
    val summary: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @Contextual @SerialName(value = "versionId")
    val versionId: java.util.UUID? = null

) {

    /**
     * 
     *
     * Values: NOT_STARTED,IN_PROGRESS,COMPLETED,NEEDS_REDOING
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "NOT_STARTED") NOT_STARTED("NOT_STARTED"),
        @SerialName(value = "IN_PROGRESS") IN_PROGRESS("IN_PROGRESS"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "NEEDS_REDOING") NEEDS_REDOING("NEEDS_REDOING");
    }

}

