/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.simplicity.training.api.models.MarkedQuestion

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param attemptNumber 
 * @param correctCount 
 * @param passed 
 * @param questionCount 
 * @param questions 
 */
@Serializable

data class AttemptResultResponse (

    @SerialName(value = "attemptNumber")
    val attemptNumber: kotlin.Int? = null,

    @SerialName(value = "correctCount")
    val correctCount: kotlin.Int? = null,

    @SerialName(value = "passed")
    val passed: kotlin.Boolean? = null,

    @SerialName(value = "questionCount")
    val questionCount: kotlin.Int? = null,

    @SerialName(value = "questions")
    val questions: kotlin.collections.List<MarkedQuestion>? = null

) {


}

