/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.simplicity.training.api.models.VersionResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param assignedTeamIds 
 * @param createdAt 
 * @param draft 
 * @param moduleId 
 * @param published 
 * @param summary 
 * @param title 
 */
@Serializable

data class AuthoredModuleResponse (

    @SerialName(value = "assignedTeamIds")
    val assignedTeamIds: kotlin.collections.List<@Contextual java.util.UUID>? = null,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "draft")
    val draft: VersionResponse? = null,

    @Contextual @SerialName(value = "moduleId")
    val moduleId: java.util.UUID? = null,

    @SerialName(value = "published")
    val published: VersionResponse? = null,

    @SerialName(value = "summary")
    val summary: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null

) {


}

