/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param orgRole 
 */
@Serializable

data class ChangeOrgRoleRequest (

    @SerialName(value = "orgRole")
    val orgRole: ChangeOrgRoleRequest.OrgRole

) {

    /**
     * 
     *
     * Values: ORG_ADMIN,ORG_MEMBER
     */
    @Serializable
    enum class OrgRole(val value: kotlin.String) {
        @SerialName(value = "ORG_ADMIN") ORG_ADMIN("ORG_ADMIN"),
        @SerialName(value = "ORG_MEMBER") ORG_MEMBER("ORG_MEMBER");
    }

}

