/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param assignedToYou 
 * @param moduleId 
 * @param moduleTitle 
 * @param sectionTitle 
 */
@Serializable

data class CitationResponse (

    @SerialName(value = "assignedToYou")
    val assignedToYou: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "moduleId")
    val moduleId: java.util.UUID? = null,

    @SerialName(value = "moduleTitle")
    val moduleTitle: kotlin.String? = null,

    @SerialName(value = "sectionTitle")
    val sectionTitle: kotlin.String? = null

) {


}

