/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email 
 * @param orgRole 
 * @param teamId 
 * @param teamRole 
 */
@Serializable

data class CreateInvitationRequest (

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "orgRole")
    val orgRole: CreateInvitationRequest.OrgRole,

    @Contextual @SerialName(value = "teamId")
    val teamId: java.util.UUID? = null,

    @SerialName(value = "teamRole")
    val teamRole: CreateInvitationRequest.TeamRole? = null

) {

    /**
     * 
     *
     * Values: ORG_ADMIN,ORG_MEMBER
     */
    @Serializable
    enum class OrgRole(val value: kotlin.String) {
        @SerialName(value = "ORG_ADMIN") ORG_ADMIN("ORG_ADMIN"),
        @SerialName(value = "ORG_MEMBER") ORG_MEMBER("ORG_MEMBER");
    }
    /**
     * 
     *
     * Values: TEAM_ADMIN,TEAM_MEMBER
     */
    @Serializable
    enum class TeamRole(val value: kotlin.String) {
        @SerialName(value = "TEAM_ADMIN") TEAM_ADMIN("TEAM_ADMIN"),
        @SerialName(value = "TEAM_MEMBER") TEAM_MEMBER("TEAM_MEMBER");
    }

}

