/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.simplicity.training.api.models.OrganisationMembershipResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param activeOrganisationId 
 * @param email 
 * @param fullName 
 * @param id 
 * @param organisations 
 * @param phone 
 * @param platformRole 
 * @param professionalRole 
 * @param profileCompleted 
 * @param status 
 */
@Serializable

data class CurrentUserResponse (

    @Contextual @SerialName(value = "activeOrganisationId")
    val activeOrganisationId: java.util.UUID? = null,

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "fullName")
    val fullName: kotlin.String? = null,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @SerialName(value = "organisations")
    val organisations: kotlin.collections.List<OrganisationMembershipResponse>? = null,

    @SerialName(value = "phone")
    val phone: kotlin.String? = null,

    @SerialName(value = "platformRole")
    val platformRole: CurrentUserResponse.PlatformRole? = null,

    @SerialName(value = "professionalRole")
    val professionalRole: kotlin.String? = null,

    @SerialName(value = "profileCompleted")
    val profileCompleted: kotlin.Boolean? = null,

    @SerialName(value = "status")
    val status: CurrentUserResponse.Status? = null

) {

    /**
     * 
     *
     * Values: SUPER_ADMIN,STANDARD
     */
    @Serializable
    enum class PlatformRole(val value: kotlin.String) {
        @SerialName(value = "SUPER_ADMIN") SUPER_ADMIN("SUPER_ADMIN"),
        @SerialName(value = "STANDARD") STANDARD("STANDARD");
    }
    /**
     * 
     *
     * Values: ACTIVE,INVITED,DEACTIVATED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "INVITED") INVITED("INVITED"),
        @SerialName(value = "DEACTIVATED") DEACTIVATED("DEACTIVATED");
    }

}

