/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param email 
 * @param expiresAt 
 * @param id 
 * @param orgRole 
 * @param status 
 * @param teamId 
 * @param teamName 
 * @param teamRole 
 */
@Serializable

data class InvitationResponse (

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @Contextual @SerialName(value = "expiresAt")
    val expiresAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @SerialName(value = "orgRole")
    val orgRole: InvitationResponse.OrgRole? = null,

    @SerialName(value = "status")
    val status: InvitationResponse.Status? = null,

    @Contextual @SerialName(value = "teamId")
    val teamId: java.util.UUID? = null,

    @SerialName(value = "teamName")
    val teamName: kotlin.String? = null,

    @SerialName(value = "teamRole")
    val teamRole: InvitationResponse.TeamRole? = null

) {

    /**
     * 
     *
     * Values: ORG_ADMIN,ORG_MEMBER
     */
    @Serializable
    enum class OrgRole(val value: kotlin.String) {
        @SerialName(value = "ORG_ADMIN") ORG_ADMIN("ORG_ADMIN"),
        @SerialName(value = "ORG_MEMBER") ORG_MEMBER("ORG_MEMBER");
    }
    /**
     * 
     *
     * Values: PENDING,ACCEPTED,REVOKED,EXPIRED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "PENDING") PENDING("PENDING"),
        @SerialName(value = "ACCEPTED") ACCEPTED("ACCEPTED"),
        @SerialName(value = "REVOKED") REVOKED("REVOKED"),
        @SerialName(value = "EXPIRED") EXPIRED("EXPIRED");
    }
    /**
     * 
     *
     * Values: TEAM_ADMIN,TEAM_MEMBER
     */
    @Serializable
    enum class TeamRole(val value: kotlin.String) {
        @SerialName(value = "TEAM_ADMIN") TEAM_ADMIN("TEAM_ADMIN"),
        @SerialName(value = "TEAM_MEMBER") TEAM_MEMBER("TEAM_MEMBER");
    }

}

