/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param chosenOptionId 
 * @param correctOptionId 
 * @param explanation 
 * @param prompt 
 * @param questionId 
 * @param wasCorrect 
 */
@Serializable

data class MarkedQuestion (

    @Contextual @SerialName(value = "chosenOptionId")
    val chosenOptionId: java.util.UUID? = null,

    @Contextual @SerialName(value = "correctOptionId")
    val correctOptionId: java.util.UUID? = null,

    @SerialName(value = "explanation")
    val explanation: kotlin.String? = null,

    @SerialName(value = "prompt")
    val prompt: kotlin.String? = null,

    @Contextual @SerialName(value = "questionId")
    val questionId: java.util.UUID? = null,

    @SerialName(value = "wasCorrect")
    val wasCorrect: kotlin.Boolean? = null

) {


}

