/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param assetId 
 * @param createdAt 
 * @param durationSeconds 
 * @param failureReason 
 * @param filename 
 * @param hasCaptions 
 * @param sizeBytes 
 * @param status 
 */
@Serializable

data class MediaAssetResponse (

    @Contextual @SerialName(value = "assetId")
    val assetId: java.util.UUID? = null,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "durationSeconds")
    val durationSeconds: kotlin.Int? = null,

    @SerialName(value = "failureReason")
    val failureReason: kotlin.String? = null,

    @SerialName(value = "filename")
    val filename: kotlin.String? = null,

    @SerialName(value = "hasCaptions")
    val hasCaptions: kotlin.Boolean? = null,

    @SerialName(value = "sizeBytes")
    val sizeBytes: kotlin.Long? = null,

    @SerialName(value = "status")
    val status: kotlin.String? = null

) {


}

