/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param country 
 * @param createdAt 
 * @param id 
 * @param name 
 * @param organisationType 
 * @param slug 
 */
@Serializable

data class OrganisationResponse (

    @SerialName(value = "country")
    val country: kotlin.String? = null,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "organisationType")
    val organisationType: OrganisationResponse.OrganisationType? = null,

    @SerialName(value = "slug")
    val slug: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: HOSPITAL,CLINIC,UNIVERSITY,COMPANY,OTHER
     */
    @Serializable
    enum class OrganisationType(val value: kotlin.String) {
        @SerialName(value = "HOSPITAL") HOSPITAL("HOSPITAL"),
        @SerialName(value = "CLINIC") CLINIC("CLINIC"),
        @SerialName(value = "UNIVERSITY") UNIVERSITY("UNIVERSITY"),
        @SerialName(value = "COMPANY") COMPANY("COMPANY"),
        @SerialName(value = "OTHER") OTHER("OTHER");
    }

}

