/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.simplicity.training.api.models.TeamMembershipResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param orgId 
 * @param orgRole 
 * @param organisationType 
 * @param slug 
 * @param teams 
 */
@Serializable

data class OrganisationMembershipResponse (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @Contextual @SerialName(value = "orgId")
    val orgId: java.util.UUID? = null,

    @SerialName(value = "orgRole")
    val orgRole: OrganisationMembershipResponse.OrgRole? = null,

    @SerialName(value = "organisationType")
    val organisationType: OrganisationMembershipResponse.OrganisationType? = null,

    @SerialName(value = "slug")
    val slug: kotlin.String? = null,

    @SerialName(value = "teams")
    val teams: kotlin.collections.List<TeamMembershipResponse>? = null

) {

    /**
     * 
     *
     * Values: ORG_ADMIN,ORG_MEMBER
     */
    @Serializable
    enum class OrgRole(val value: kotlin.String) {
        @SerialName(value = "ORG_ADMIN") ORG_ADMIN("ORG_ADMIN"),
        @SerialName(value = "ORG_MEMBER") ORG_MEMBER("ORG_MEMBER");
    }
    /**
     * 
     *
     * Values: HOSPITAL,CLINIC,UNIVERSITY,COMPANY,OTHER
     */
    @Serializable
    enum class OrganisationType(val value: kotlin.String) {
        @SerialName(value = "HOSPITAL") HOSPITAL("HOSPITAL"),
        @SerialName(value = "CLINIC") CLINIC("CLINIC"),
        @SerialName(value = "UNIVERSITY") UNIVERSITY("UNIVERSITY"),
        @SerialName(value = "COMPANY") COMPANY("COMPANY"),
        @SerialName(value = "OTHER") OTHER("OTHER");
    }

}

