/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email 
 * @param fullName 
 * @param joinedAt 
 * @param membershipStatus 
 * @param orgRole 
 * @param professionalRole 
 * @param userId 
 * @param userStatus 
 */
@Serializable

data class OrgMemberResponse (

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "fullName")
    val fullName: kotlin.String? = null,

    @Contextual @SerialName(value = "joinedAt")
    val joinedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "membershipStatus")
    val membershipStatus: OrgMemberResponse.MembershipStatus? = null,

    @SerialName(value = "orgRole")
    val orgRole: OrgMemberResponse.OrgRole? = null,

    @SerialName(value = "professionalRole")
    val professionalRole: kotlin.String? = null,

    @Contextual @SerialName(value = "userId")
    val userId: java.util.UUID? = null,

    @SerialName(value = "userStatus")
    val userStatus: OrgMemberResponse.UserStatus? = null

) {

    /**
     * 
     *
     * Values: ACTIVE,SUSPENDED
     */
    @Serializable
    enum class MembershipStatus(val value: kotlin.String) {
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "SUSPENDED") SUSPENDED("SUSPENDED");
    }
    /**
     * 
     *
     * Values: ORG_ADMIN,ORG_MEMBER
     */
    @Serializable
    enum class OrgRole(val value: kotlin.String) {
        @SerialName(value = "ORG_ADMIN") ORG_ADMIN("ORG_ADMIN"),
        @SerialName(value = "ORG_MEMBER") ORG_MEMBER("ORG_MEMBER");
    }
    /**
     * 
     *
     * Values: ACTIVE,INVITED,DEACTIVATED
     */
    @Serializable
    enum class UserStatus(val value: kotlin.String) {
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "INVITED") INVITED("INVITED"),
        @SerialName(value = "DEACTIVATED") DEACTIVATED("DEACTIVATED");
    }

}

