/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.simplicity.training.api.models.OptionInput

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param options 
 * @param prompt 
 * @param explanation 
 */
@Serializable

data class QuestionInput (

    @SerialName(value = "options")
    val options: kotlin.collections.List<OptionInput>,

    @SerialName(value = "prompt")
    val prompt: kotlin.String,

    @SerialName(value = "explanation")
    val explanation: kotlin.String? = null

) {


}

