/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.simplicity.training.api.models.QuizQuestionResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param attemptCount 
 * @param passed 
 * @param questions 
 * @param versionId 
 */
@Serializable

data class QuizResponse (

    @SerialName(value = "attemptCount")
    val attemptCount: kotlin.Int? = null,

    @SerialName(value = "passed")
    val passed: kotlin.Boolean? = null,

    @SerialName(value = "questions")
    val questions: kotlin.collections.List<QuizQuestionResponse>? = null,

    @Contextual @SerialName(value = "versionId")
    val versionId: java.util.UUID? = null

) {


}

