/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.simplicity.training.api.models.QuizOptionResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param options 
 * @param position 
 * @param prompt 
 * @param questionId 
 */
@Serializable

data class QuizQuestionResponse (

    @SerialName(value = "options")
    val options: kotlin.collections.List<QuizOptionResponse>? = null,

    @SerialName(value = "position")
    val position: kotlin.Int? = null,

    @SerialName(value = "prompt")
    val prompt: kotlin.String? = null,

    @Contextual @SerialName(value = "questionId")
    val questionId: java.util.UUID? = null

) {


}

