/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param body 
 * @param createdAt 
 * @param id 
 * @param title 
 * @param updatedAt 
 */
@Serializable

data class ReflectionResponse (

    @SerialName(value = "body")
    val body: kotlin.String? = null,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

