/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param contentType 
 * @param filename 
 * @param sizeBytes 
 */
@Serializable

data class RegisterUploadRequest (

    @SerialName(value = "contentType")
    val contentType: kotlin.String,

    @SerialName(value = "filename")
    val filename: kotlin.String,

    @SerialName(value = "sizeBytes")
    val sizeBytes: kotlin.Long? = null

) {


}

