/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param body 
 * @param mediaAssetId 
 * @param position 
 * @param sectionId 
 * @param title 
 */
@Serializable

data class SectionResponse (

    @SerialName(value = "body")
    val body: kotlin.String? = null,

    @Contextual @SerialName(value = "mediaAssetId")
    val mediaAssetId: java.util.UUID? = null,

    @SerialName(value = "position")
    val position: kotlin.Int? = null,

    @Contextual @SerialName(value = "sectionId")
    val sectionId: java.util.UUID? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null

) {


}

