/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param description 
 * @param id 
 * @param memberCount 
 * @param name 
 * @param orgId 
 */
@Serializable

data class TeamResponse (

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @SerialName(value = "memberCount")
    val memberCount: kotlin.Int? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @Contextual @SerialName(value = "orgId")
    val orgId: java.util.UUID? = null

) {


}

