/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.simplicity.training.api.models

import io.simplicity.training.api.models.AuthoredQuestionResponse
import io.simplicity.training.api.models.SectionResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param publishedAt 
 * @param questions 
 * @param sections 
 * @param status 
 * @param supersedesCompletions 
 * @param versionId 
 * @param versionNumber 
 */
@Serializable

data class VersionResponse (

    @Contextual @SerialName(value = "publishedAt")
    val publishedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "questions")
    val questions: kotlin.collections.List<AuthoredQuestionResponse>? = null,

    @SerialName(value = "sections")
    val sections: kotlin.collections.List<SectionResponse>? = null,

    @SerialName(value = "status")
    val status: kotlin.String? = null,

    @SerialName(value = "supersedesCompletions")
    val supersedesCompletions: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "versionId")
    val versionId: java.util.UUID? = null,

    @SerialName(value = "versionNumber")
    val versionNumber: kotlin.Int? = null

) {


}

