/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddTeamMemberRequest { 
    teamRole: AddTeamMemberRequest.TeamRoleEnum;
    userId: string;
}
export namespace AddTeamMemberRequest {
    export const TeamRoleEnum = {
        TEAM_ADMIN: 'TEAM_ADMIN',
        TEAM_MEMBER: 'TEAM_MEMBER',
    } as const;
    export type TeamRoleEnum = typeof TeamRoleEnum[keyof typeof TeamRoleEnum];
}


