/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddTeamMemberRequest { 
    teamRole: AddTeamMemberRequestTeamRoleEnum;
    userId: string;
}
export enum AddTeamMemberRequestTeamRoleEnum {
    TEAM_ADMIN = 'TEAM_ADMIN',
    TEAM_MEMBER = 'TEAM_MEMBER'
};



