/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssignedModuleResponse { 
    completedSectionCount?: number;
    moduleId?: string;
    sectionCount?: number;
    status?: AssignedModuleResponse.StatusEnum;
    summary?: string;
    title?: string;
    versionId?: string;
}
export namespace AssignedModuleResponse {
    export const StatusEnum = {
        NOT_STARTED: 'NOT_STARTED',
        IN_PROGRESS: 'IN_PROGRESS',
        COMPLETED: 'COMPLETED',
        NEEDS_REDOING: 'NEEDS_REDOING',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


