/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthoredOptionResponse } from './authored-option-response';


export interface AuthoredQuestionResponse { 
    explanation?: string;
    options?: Array<AuthoredOptionResponse>;
    position?: number;
    prompt?: string;
    questionId?: string;
}

