/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChangeOrgRoleRequest { 
    orgRole: ChangeOrgRoleRequestOrgRoleEnum;
}
export enum ChangeOrgRoleRequestOrgRoleEnum {
    ORG_ADMIN = 'ORG_ADMIN',
    ORG_MEMBER = 'ORG_MEMBER'
};



