/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CitationResponse { 
    assignedToYou?: boolean;
    moduleId?: string;
    moduleTitle?: string;
    sectionTitle?: string;
}

