/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateInvitationRequest { 
    email: string;
    orgRole: CreateInvitationRequest.OrgRoleEnum;
    teamId?: string;
    teamRole?: CreateInvitationRequest.TeamRoleEnum;
}
export namespace CreateInvitationRequest {
    export const OrgRoleEnum = {
        ORG_ADMIN: 'ORG_ADMIN',
        ORG_MEMBER: 'ORG_MEMBER',
    } as const;
    export type OrgRoleEnum = typeof OrgRoleEnum[keyof typeof OrgRoleEnum];
    export const TeamRoleEnum = {
        TEAM_ADMIN: 'TEAM_ADMIN',
        TEAM_MEMBER: 'TEAM_MEMBER',
    } as const;
    export type TeamRoleEnum = typeof TeamRoleEnum[keyof typeof TeamRoleEnum];
}


