/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateInvitationRequest { 
    email: string;
    orgRole: CreateInvitationRequestOrgRoleEnum;
    teamId?: string;
    teamRole?: CreateInvitationRequestTeamRoleEnum;
}
export enum CreateInvitationRequestOrgRoleEnum {
    ORG_ADMIN = 'ORG_ADMIN',
    ORG_MEMBER = 'ORG_MEMBER'
};
export enum CreateInvitationRequestTeamRoleEnum {
    TEAM_ADMIN = 'TEAM_ADMIN',
    TEAM_MEMBER = 'TEAM_MEMBER'
};



