/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateOrganisationRequest { 
    country?: string;
    name: string;
    organisationType: CreateOrganisationRequestOrganisationTypeEnum;
}
export enum CreateOrganisationRequestOrganisationTypeEnum {
    HOSPITAL = 'HOSPITAL',
    CLINIC = 'CLINIC',
    UNIVERSITY = 'UNIVERSITY',
    COMPANY = 'COMPANY',
    OTHER = 'OTHER'
};



