/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganisationMembershipResponse } from './organisation-membership-response';


export interface CurrentUserResponse { 
    email?: string;
    fullName?: string;
    id?: string;
    organisations?: Array<OrganisationMembershipResponse>;
    phone?: string;
    platformRole?: CurrentUserResponsePlatformRoleEnum;
    professionalRole?: string;
    profileCompleted?: boolean;
    status?: CurrentUserResponseStatusEnum;
}
export enum CurrentUserResponsePlatformRoleEnum {
    SUPER_ADMIN = 'SUPER_ADMIN',
    STANDARD = 'STANDARD'
};
export enum CurrentUserResponseStatusEnum {
    ACTIVE = 'ACTIVE',
    INVITED = 'INVITED',
    DEACTIVATED = 'DEACTIVATED'
};



