/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganisationMembershipResponse } from './organisation-membership-response';


export interface CurrentUserResponse { 
    email?: string;
    fullName?: string;
    id?: string;
    organisations?: Array<OrganisationMembershipResponse>;
    phone?: string;
    platformRole?: CurrentUserResponse.PlatformRoleEnum;
    professionalRole?: string;
    profileCompleted?: boolean;
    status?: CurrentUserResponse.StatusEnum;
}
export namespace CurrentUserResponse {
    export const PlatformRoleEnum = {
        SUPER_ADMIN: 'SUPER_ADMIN',
        STANDARD: 'STANDARD',
    } as const;
    export type PlatformRoleEnum = typeof PlatformRoleEnum[keyof typeof PlatformRoleEnum];
    export const StatusEnum = {
        ACTIVE: 'ACTIVE',
        INVITED: 'INVITED',
        DEACTIVATED: 'DEACTIVATED',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


