/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvitationResponse { 
    createdAt?: string;
    email?: string;
    expiresAt?: string;
    id?: string;
    orgRole?: InvitationResponseOrgRoleEnum;
    status?: InvitationResponseStatusEnum;
    teamId?: string;
    teamName?: string;
    teamRole?: InvitationResponseTeamRoleEnum;
}
export enum InvitationResponseOrgRoleEnum {
    ORG_ADMIN = 'ORG_ADMIN',
    ORG_MEMBER = 'ORG_MEMBER'
};
export enum InvitationResponseStatusEnum {
    PENDING = 'PENDING',
    ACCEPTED = 'ACCEPTED',
    REVOKED = 'REVOKED',
    EXPIRED = 'EXPIRED'
};
export enum InvitationResponseTeamRoleEnum {
    TEAM_ADMIN = 'TEAM_ADMIN',
    TEAM_MEMBER = 'TEAM_MEMBER'
};



