/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvitationResponse { 
    createdAt?: string;
    email?: string;
    expiresAt?: string;
    id?: string;
    orgRole?: InvitationResponse.OrgRoleEnum;
    status?: InvitationResponse.StatusEnum;
    teamId?: string;
    teamName?: string;
    teamRole?: InvitationResponse.TeamRoleEnum;
}
export namespace InvitationResponse {
    export const OrgRoleEnum = {
        ORG_ADMIN: 'ORG_ADMIN',
        ORG_MEMBER: 'ORG_MEMBER',
    } as const;
    export type OrgRoleEnum = typeof OrgRoleEnum[keyof typeof OrgRoleEnum];
    export const StatusEnum = {
        PENDING: 'PENDING',
        ACCEPTED: 'ACCEPTED',
        REVOKED: 'REVOKED',
        EXPIRED: 'EXPIRED',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const TeamRoleEnum = {
        TEAM_ADMIN: 'TEAM_ADMIN',
        TEAM_MEMBER: 'TEAM_MEMBER',
    } as const;
    export type TeamRoleEnum = typeof TeamRoleEnum[keyof typeof TeamRoleEnum];
}


