/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvitationPreviewResponse { 
    email?: string;
    orgRole?: InvitationPreviewResponse.OrgRoleEnum;
    organisationName?: string;
    teamName?: string;
    valid?: boolean;
}
export namespace InvitationPreviewResponse {
    export const OrgRoleEnum = {
        ORG_ADMIN: 'ORG_ADMIN',
        ORG_MEMBER: 'ORG_MEMBER',
    } as const;
    export type OrgRoleEnum = typeof OrgRoleEnum[keyof typeof OrgRoleEnum];
}


