/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectionResponse } from './section-response';


export interface LearnerModuleResponse { 
    completedSectionIds?: Array<string>;
    hasQuiz?: boolean;
    moduleId?: string;
    quizPassed?: boolean;
    sections?: Array<SectionResponse>;
    status?: LearnerModuleResponse.StatusEnum;
    summary?: string;
    title?: string;
    versionId?: string;
}
export namespace LearnerModuleResponse {
    export const StatusEnum = {
        NOT_STARTED: 'NOT_STARTED',
        IN_PROGRESS: 'IN_PROGRESS',
        COMPLETED: 'COMPLETED',
        NEEDS_REDOING: 'NEEDS_REDOING',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


