/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarkedQuestion { 
    chosenOptionId?: string;
    correctOptionId?: string;
    explanation?: string;
    prompt?: string;
    questionId?: string;
    wasCorrect?: boolean;
}

