/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrgMemberResponse { 
    email?: string;
    fullName?: string;
    joinedAt?: string;
    membershipStatus?: OrgMemberResponse.MembershipStatusEnum;
    orgRole?: OrgMemberResponse.OrgRoleEnum;
    professionalRole?: string;
    userId?: string;
    userStatus?: OrgMemberResponse.UserStatusEnum;
}
export namespace OrgMemberResponse {
    export const MembershipStatusEnum = {
        ACTIVE: 'ACTIVE',
        SUSPENDED: 'SUSPENDED',
    } as const;
    export type MembershipStatusEnum = typeof MembershipStatusEnum[keyof typeof MembershipStatusEnum];
    export const OrgRoleEnum = {
        ORG_ADMIN: 'ORG_ADMIN',
        ORG_MEMBER: 'ORG_MEMBER',
    } as const;
    export type OrgRoleEnum = typeof OrgRoleEnum[keyof typeof OrgRoleEnum];
    export const UserStatusEnum = {
        ACTIVE: 'ACTIVE',
        INVITED: 'INVITED',
        DEACTIVATED: 'DEACTIVATED',
    } as const;
    export type UserStatusEnum = typeof UserStatusEnum[keyof typeof UserStatusEnum];
}


