/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrgMemberResponse { 
    email?: string;
    fullName?: string;
    joinedAt?: string;
    membershipStatus?: OrgMemberResponseMembershipStatusEnum;
    orgRole?: OrgMemberResponseOrgRoleEnum;
    professionalRole?: string;
    userId?: string;
    userStatus?: OrgMemberResponseUserStatusEnum;
}
export enum OrgMemberResponseMembershipStatusEnum {
    ACTIVE = 'ACTIVE',
    SUSPENDED = 'SUSPENDED'
};
export enum OrgMemberResponseOrgRoleEnum {
    ORG_ADMIN = 'ORG_ADMIN',
    ORG_MEMBER = 'ORG_MEMBER'
};
export enum OrgMemberResponseUserStatusEnum {
    ACTIVE = 'ACTIVE',
    INVITED = 'INVITED',
    DEACTIVATED = 'DEACTIVATED'
};



