/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrganisationResponse { 
    country?: string;
    createdAt?: string;
    id?: string;
    name?: string;
    organisationType?: OrganisationResponseOrganisationTypeEnum;
    slug?: string;
}
export enum OrganisationResponseOrganisationTypeEnum {
    HOSPITAL = 'HOSPITAL',
    CLINIC = 'CLINIC',
    UNIVERSITY = 'UNIVERSITY',
    COMPANY = 'COMPANY',
    OTHER = 'OTHER'
};



