/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamMembershipResponse } from './team-membership-response';


export interface OrganisationMembershipResponse { 
    name?: string;
    orgId?: string;
    orgRole?: OrganisationMembershipResponseOrgRoleEnum;
    organisationType?: OrganisationMembershipResponseOrganisationTypeEnum;
    slug?: string;
    teams?: Array<TeamMembershipResponse>;
}
export enum OrganisationMembershipResponseOrgRoleEnum {
    ORG_ADMIN = 'ORG_ADMIN',
    ORG_MEMBER = 'ORG_MEMBER'
};
export enum OrganisationMembershipResponseOrganisationTypeEnum {
    HOSPITAL = 'HOSPITAL',
    CLINIC = 'CLINIC',
    UNIVERSITY = 'UNIVERSITY',
    COMPANY = 'COMPANY',
    OTHER = 'OTHER'
};



