/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrganisationResponse { 
    country?: string;
    createdAt?: string;
    id?: string;
    name?: string;
    organisationType?: OrganisationResponse.OrganisationTypeEnum;
    slug?: string;
}
export namespace OrganisationResponse {
    export const OrganisationTypeEnum = {
        HOSPITAL: 'HOSPITAL',
        CLINIC: 'CLINIC',
        UNIVERSITY: 'UNIVERSITY',
        COMPANY: 'COMPANY',
        OTHER: 'OTHER',
    } as const;
    export type OrganisationTypeEnum = typeof OrganisationTypeEnum[keyof typeof OrganisationTypeEnum];
}


