/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamMembershipResponse } from './team-membership-response';


export interface OrganisationMembershipResponse { 
    name?: string;
    orgId?: string;
    orgRole?: OrganisationMembershipResponse.OrgRoleEnum;
    organisationType?: OrganisationMembershipResponse.OrganisationTypeEnum;
    slug?: string;
    teams?: Array<TeamMembershipResponse>;
}
export namespace OrganisationMembershipResponse {
    export const OrgRoleEnum = {
        ORG_ADMIN: 'ORG_ADMIN',
        ORG_MEMBER: 'ORG_MEMBER',
    } as const;
    export type OrgRoleEnum = typeof OrgRoleEnum[keyof typeof OrgRoleEnum];
    export const OrganisationTypeEnum = {
        HOSPITAL: 'HOSPITAL',
        CLINIC: 'CLINIC',
        UNIVERSITY: 'UNIVERSITY',
        COMPANY: 'COMPANY',
        OTHER: 'OTHER',
    } as const;
    export type OrganisationTypeEnum = typeof OrganisationTypeEnum[keyof typeof OrganisationTypeEnum];
}


