/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizQuestionResponse } from './quiz-question-response';


export interface QuizResponse { 
    attemptCount?: number;
    passed?: boolean;
    questions?: Array<QuizQuestionResponse>;
    versionId?: string;
}

