/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizOptionResponse } from './quiz-option-response';


export interface QuizQuestionResponse { 
    options?: Array<QuizOptionResponse>;
    position?: number;
    prompt?: string;
    questionId?: string;
}

