/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionInput } from './question-input';


export interface ReplaceQuizRequest { 
    questions: Array<QuestionInput>;
}

