/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectionInput } from './section-input';


export interface ReplaceSectionsRequest { 
    sections: Array<SectionInput>;
}

