/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnswerInput } from './answer-input';


export interface SubmitAttemptRequest { 
    answers: Array<AnswerInput>;
}

