/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TeamMemberDetailResponse { 
    email?: string;
    fullName?: string;
    joinedAt?: string;
    professionalRole?: string;
    teamRole?: TeamMemberDetailResponseTeamRoleEnum;
    userId?: string;
}
export enum TeamMemberDetailResponseTeamRoleEnum {
    TEAM_ADMIN = 'TEAM_ADMIN',
    TEAM_MEMBER = 'TEAM_MEMBER'
};



