/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TeamMembershipResponse { 
    name?: string;
    teamId?: string;
    teamRole?: TeamMembershipResponseTeamRoleEnum;
}
export enum TeamMembershipResponseTeamRoleEnum {
    TEAM_ADMIN = 'TEAM_ADMIN',
    TEAM_MEMBER = 'TEAM_MEMBER'
};



