/**
 * Simplicity training API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthoredQuestionResponse } from './authored-question-response';
import { SectionResponse } from './section-response';


export interface VersionResponse { 
    publishedAt?: string;
    questions?: Array<AuthoredQuestionResponse>;
    sections?: Array<SectionResponse>;
    status?: string;
    supersedesCompletions?: boolean;
    versionId?: string;
    versionNumber?: number;
}

